arch: arm64
os: linux
dist: focal
branches:
  only:
    - main

language: generic

install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-ARM64.deb
- sudo dpkg -i /tmp/hugo.deb

script:
  - HUGO_ENV=production hugo --gc --minify -v

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/public
  on:
    branch: main

notifications:
  email:
      recipients:
        - jayin920805@gmail.com
      on_success: always
      on_failure: always