arch: arm64
os: linux
dist: focal
branches:
  only:
    - main

language: generic

install:
- sudo snap install hugo

script:
  - HUGO_ENV=production hugo --gc --minify -v

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/public
  on:
    branch: mainmaster

notifications:
  email:
      recipients:
        - jayin920805@gmail.com
      on_success: always
      on_failure: always