baseurl = "https://blog.jayinnn.dev/"
languageCode = "zh-tw"
title = "Jayinnn's Blog"
theme = "archie"
copyright = "Jayinnn © CC BY-NC-SA 4.0"

# Code Highlight — configured under [markup.highlight] below

[pagination]
  pagerSize = 10 # articles per page


[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Blog about My Daily Life"
	mainSections = ["posts"]

# Social Tags

[[params.social]]
  name = "Personal Page"
  icon = "home"
  url = "https://jayinnn.dev"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/jayin92/"

[[params.social]]
  name = "Linkedin"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/jayinnn/"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:me@jayinnn.dev"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[markup]
  [markup.highlight]
    style = "monokai"
    codeFences = true
    guessSyntax = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5