baseurl = "https://blog.jayinnn.dev/"
languageCode = "zh-tw"
title = "Jayinnn's Blog"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page


[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Blog about My Daily Life"

# Social Tags

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/jayin92/"

[[params.social]]
  name = "Facebook"
  icon = "facebook"
  url = "https://www.facebook.com/jayinnn"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:me@jayinnn.dev"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Diaries"
url = "/diaries"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5


[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5